export const findColour = (country) => {
  return countryColours[country][0];
};

export const darkBlue = '#3B3483',
     lightBlue = '#00A4E5',
       darkRed = '#CE001F',
         white = '#eeeeee',
     brightRed = '#FF164C',
     darkGreen = '#008A4F',
    lightGreen = '#0FC070',
   brightGreen = '#00B427',
        yellow = '#FFE500',
         black = '#000000',
        orange = '#FF821C',
          blue = '#0060B0',
    darkYellow = '#FFC900',
         spare = ["#FD7F6F", "#7EB0D5", "#B2E061", "#BD7EBE", "#FFB55A", "#FFEE65", "#BEB9DB", "#FDCCE5", "#8BD3C7"];

const countryColours = {
            'australia': [darkBlue, darkRed, white],
            'austria': [brightRed, white],
            'brazil': [darkGreen, yellow, darkBlue],
            'canada': [brightRed, white],
            'china': [brightRed, darkYellow],
            'czech republic': [blue, darkRed, white],
            'denmark': [darkRed, white],
            'estonia': [black, blue, white],
            'ethiopia': [lightBlue, darkGreen, darkRed, darkYellow],
            'finland': [darkBlue, white],
            'france': [blue, brightRed, white],
            'germany': [darkYellow, black, brightRed],
            'ghana': [darkGreen, darkYellow, darkRed, black],
            'greece': [blue, white],
            'hungary': [darkGreen, darkRed, white],
            'iceland': [blue, darkRed, white],
            'india': [lightGreen, orange, darkBlue],
            'indonesia': [brightRed, white],
            'ireland': [lightGreen, orange],
            'israel': [darkBlue, white],
            'italy': [darkGreen, darkRed, white],
            'jamaica': [brightGreen, yellow, black],
            'japan': [brightRed, white],
            'kenya': [darkGreen, darkRed, black],
            'latvia': [darkRed, white],
            'luxembourg': [lightBlue, brightRed],
            'new zealand': [darkBlue, darkRed],
            'nigeria': [darkGreen, white],
            'norway': [darkBlue, brightRed],
            'romania': [darkBlue, darkYellow, darkRed],
            'south africa': [darkGreen, black, darkBlue, darkRed, white],
            'south korea': [white, black, darkBlue, darkRed],
            'spain': [darkRed, darkYellow],
            'sweden': [blue, darkYellow],
            'switzerland': [brightRed, white],
            'turkey': [darkRed, white],
            'united kingdom': [darkBlue, darkRed, white],
            'united states': [darkBlue, darkRed, white],
            'vietnam': [brightRed, yellow],
        };